### ISSUE TITLE
Error building: Can't find -ludev

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/rpi-image-builder#1]
From when I was trying to generate an 0.3.1 release: https://travis-ci.org/mozilla-iot/rpi-image-builder/builds/350586550#L2251

More builds/debugging attempts: https://travis-ci.org/hobinjk/rpi-image-builder/builds

**Comment by mrstegeman** [comment]
@hobinjk Is this fixed?

**Comment by dhylands** [comment]
It should be. I've been using rpi-image-builder for all of the recent releases and they've been working fine.

For 0.5, libudev is installed directly into the docker cross compiler image we use:
https://github.com/mozilla-iot/docker-raspberry-pi-cross-compiler/blob/rpxc-stretch/Dockerfile#L58
